name: Deployment of React App
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    env: 
      VERCEL_TIC_TAC_TOE_PROJECT_ID: ${{secrets.VERCEL_TIC_TAC_TOE_PROJECT_ID}}
      VERCEL_TIC_TAC_TOE_ORG_ID: ${{secrets.VERCEL_TIC_TAC_TOE_ORG_ID}}
      VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}
    steps:
         - uses: actions/checkout@v2
         - uses: actions/setup-node@v2
           with:
             node-version: '14.17.0'
         - name: Install Node modules
           run: yarn
         - name: Build the Project
           run: yarn build   
         - name: Sets the vercel env
           run: |
             cd build
             mkdir .vercel
             cd .vercel
             touch project.json
             echo '{\"orgId\":\"$VERCEL_TIC_TAC_TOE_ORG_ID\",\"projectId\":\"$VERCEL_TIC_TAC_TOE_PROJECT_ID\"}' > project.json
        
         - name: Deploying the project
           run: yarn deploy
         - name: Setup Finished
           run: echo "THE PROJECT IS UP AND RUNNING" 